# Generated by Django 4.2.7 on 2023-11-07 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sim_api_app', '0002_trait_effect_alter_trait_ambition_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='trait',
            name='trait_subtype',
            field=models.CharField(blank=True, null=True),
        ),
    ]
